### ISSUE TITLE
Remove `.env`

### ISSUE THREAD

**Issue by seyeong-han** [pradyun0414/resia-assessment#1]
It was great to see your Amplify project, and I really liked it!

But while reviewing your codes, I saw you reveal the `.env` file on the public code.
You should remove it and add the `.env` file to your `.gitignore` for future safety.

Thanks!

**Comment by pradyun0414** [comment]
Thank you for noticing that! I actually didn't end up using the .env at all since what the secrets were supposedly not confidential information (I left it in the code), but I forgot to delete the env file after that. I will delete it now - thank you
